config/routes.rb
Rails.application.routes.draw do
  root to: "scribe#index"
  resources :categories
  resources :users, only: %i[index show create destroy update edit]
  resource :session
  # User routes
  get '/signup' => 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :order, numericality: { only_integer: true, greater_than: 0 }

  belongs_to :parent, class_name: "Category", optional: true
  has_many :children, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy

  def parent_title
    # it may not have a parent
    parent.try(:title)
  end

  def has_parent?
    parent.present?
  end

  def has_children?
    children.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
  validates :email, uniqueness: true
  validates :name, presence: true
  validates :password, length: { in: 8..20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Authenticate
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category created successfully!'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category updated successfully!'
    else
      render action: 'edit'
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path, notice: 'Category was destroyed successfully'
    else
      render action: 'index', alert: "Category #{category.name} can not be destroyed"
    end
  end

  private

  def category_params
    params.require(:category).permit(:title, :description, :parent_id)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/concerns/authenticate.rb
module Authenticate
  def authenticate
    unless sign_in?
      redirect_to new_session_path
    end
  end

  def sign_in?
    current_user.present?
  end

  def current_user
    session[:user_id]
  end

  def login_as(user)
    session[:user_id] = user.id
  end

  def sign_in_as(session_params)
    user = User.find_by_email(session_params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(session_params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to root_path
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to new_session_path
    end
  end
end

app/controllers/scribe_controller.rb
class ScribeController < ApplicationController
  before_action :authenticate

  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    sign_in_as(session_params)
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.create(user_params)
    if @user.save
      login_as(@user)
      redirect_to user_path(@user), notice: 'User created successfully'
    else
      redirect_to signup_path, alert: 'User could not be created'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_errors_for(object=nil)
    render('shared/form_errors', object: object) unless object.errors.count < 1
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_category.html.erb
<tr>
  <td><%= category.parent_title %></td>
  <td><%= category.title %></td>
  <td><%= category.description %></td>
  <td>
    <span id="<%= "category_#{category.id}" %>">
      <%= link_to 'Show', category_path(category) %>
      <%= link_to 'Edit', edit_category_path(category) %>
      <%= link_to 'Delete',  { action: :destroy, id: category.id },
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
      </span>
  </td>
</tr>

app/views/categories/_children.html.erb
<% unless children.nil? %>
  <ul>
    <% children.each do |child| %>
      <li><%= child.title %></li>
    <% end %>
  </ul>
<% end %>

app/views/categories/_form.html.erb
<%= form_errors_for @category %>
<%= form_for @category do |form| %>
  <%= content_for :form_errors %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :parent_id %>
    <%= form.select :parent_id,
                    options_for_select(Category.all.map{ |c| [c.title, c.id] }),
                    {}, { class: 'form-control' }
    %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>
  <%= form.submit "Submit", class: "btn btn-success" %>
<% end %>

app/views/categories/edit.html.erb
<div class="d-flex" id="wrapper">
  <%= render "shared/sidebar_menu" %>
  <div id="page-content-wrapper">
    <%= render "shared/menu" %>
    <div class="container-fluid">
      <h1 class="mt-4">Edit Category</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="d-flex" id="wrapper">
  <%= render "shared/sidebar_menu" %>
  <!-- Page Content -->
  <div id="page-content-wrapper">
    <%= render "shared/menu" %>
    <div class="container-fluid">
      <h1 class="mt-4">Categories</h1>
      <table class="table">
        <thead>
        <tr>
          <th scope="col">Parent Category</th>
          <th scope="col">Category</th>
          <th scope="col">Description</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <thbody>
          <%= render @categories %>
        </thbody>
      </table>
      <%= link_to 'Add new Category', new_category_path, class: "btn btn-success" %>
    </div>
  </div>
  <!-- /#page-content-wrapper -->
</div>

app/views/categories/new.html.erb
<div class="d-flex" id="wrapper">
  <%= render "shared/sidebar_menu" %>
  <div id="page-content-wrapper">
    <%= render "shared/menu" %>
    <div class="container-fluid">
      <h1 class="mt-4">New Category</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="d-flex" id="wrapper">
  <%= render "shared/sidebar_menu" %>
  <div id="page-content-wrapper">
    <%= render "shared/menu" %>
    <div class="container-fluid category">
      <h1 class="mt-4">Category <%= @category.title %></h1>
        <p><b>Parent Category: </b><%= @category.parent_title %></p>
        <p><b>Description: </b><%= @category.description %></p>
        <p>
          <b>Children: </b>
          <%= render 'children', children: @category.children %>
        </p>
    </div>
    <%= link_to 'List of Categories', categories_path, class: "btn btn-link" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Scribe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <!-- Menu Toggle Script -->
    <%= javascript_pack_tag 'toggled' %>
  </body>
</html>

app/views/scribe/index.html.erb
<div class="d-flex" id="wrapper">
  <%= render "shared/sidebar_menu" %>
  <!-- Page Content -->
  <div id="page-content-wrapper">
    <%= render "shared/menu" %>
    <div class="container-fluid">
      <h1 class="mt-4">Dashboard Scribe</h1>
    </div>
  </div>
  <!-- /#page-content-wrapper -->
</div>

<!-- Menu Toggle Script-->
<%#= javascript_pack_tag 'toggled' %>

app/views/shared/_form_errors.html.erb
<% content_for :form_errors do %>
  <div class="alert alert-danger" role="alert">
    <p>
      <%= pluralize(object.errors.count, "error") %> prevented the form from being saved:
    </p>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_sidebar_menu.html.erb
<div class="bg-light border-right" id="sidebar-wrapper">
  <div class="sidebar-heading">Start Bootstrap </div>
  <div class="list-group list-group-flush">
    <%= link_to 'Category',categories_path, class: 'list-group-item list-group-item-action bg-light' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
      <%= form_for @user do |form| %>
					<span class="login100-form-title p-b-33">
						New Account
					</span>

        <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
          <%= form.text_field :email, class: 'input100', placeholder: "Email" %>
          <span class="focus-input100-1"></span>
          <span class="focus-input100-2"></span>
        </div>

        <div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
          <%= form.text_field :name, class: 'input100', placeholder: "Name" %>
          <span class="focus-input100-1"></span>
          <span class="focus-input100-2"></span>
        </div>

        <div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
          <%= form.text_field :surname, class: 'input100', placeholder: "Surname" %>
          <span class="focus-input100-1"></span>
          <span class="focus-input100-2"></span>
        </div>

        <div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
          <%= form.password_field :password, class: 'input100', placeholder: "Password" %>
          <span class="focus-input100-1"></span>
          <span class="focus-input100-2"></span>
        </div>

        <div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
          <%= form.password_field :password_confirmation, class: 'input100',
                                                          placeholder: "Password Confirmation" %>

          <span class="focus-input100-1"></span>
          <span class="focus-input100-2"></span>
        </div>

        <div class="container-login100-form-btn m-t-20">
          <%= form.submit 'Sign Up', class: "login100-form-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Show User</h1>
<div id="user">
  <p><b>Email: </b><%= @user.email %></p>
  <p><b>Name: </b><%= @user.name %></p>
  <p><b>Surname: </b><%= @user.surname %></p>
</div>